version: '3.9'
services:
  db:
    build:
      context: ./db
    volumes:
      - ./db:/db
    restart: on-failure:5
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      POSTGRES_DB: '${PG_DATABASE}'
  server:
    build:
      context: ./
    volumes:
      - ./log:/app/log
      - ./build:/app/build
    depends_on:
      - db
    restart: on-failure:5
    ports:
      - '${PORT}:${PORT}'
networks:
  default:
    name: rs-net
