version: '3.9'
services:
  db:
    build: ./db
    volumes:
      - data:/var/lib/postgresql/data
    restart: on-failure:5
    ports:
      - '${PGPORT}:${PGPORT}'
    env_file:
      - './.env'
  server:
    build:
      context: ./
    volumes:
      - ./log:/app/log
      - ./build:/app/build
    depends_on:
      - db
    restart: on-failure:5
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - './.env'
networks:
  default:
    name: rs-net
volumes:
  data:
    external: true
